name: Perl CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.34'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v3
      - name: perl -V
        run: perl -V
      # - run: prove -lv t
      - run: perl -MDevel::Cover prove -Ilib -r t

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # upload-coverage:
  #   runs-on: ubuntu-latest
  #   needs: perl
  #   steps:
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v2
  #       env:
  #         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}