name: Perl CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.34'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v3
      - name: perl -V
        run: perl -V

      - name: Run tests with coverage
        run: |
          cpanm --notest Devel::Cover
          PERL5OPT=-MDevel::Cover prove -Ilib -r t
        env:
          PERL5LIB: /home/runner/.cpanm/work/1634619180.12016/Devel-Cover-1.40/blib/lib:/home/runner/.cpanm/work/1634619180.12016/Devel-Cover-1.40/blib/arch
      
      - name: Convert Devel::Cover HTML report to Lcov
        run: |
          cd cover_db
          cover -report lcov
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: perl5
          files: cover_db/lcov-report/coverage.lcov