name: Codecov

on:
  push:

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: perl:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cpanm --quiet --notest Module::Build Devel::Cover Devel::Cover::Report::Codecov

      - name: Build project
        run: perl Makefile.PL

      - name: Run tests and generate coverage report
        run: cover -test -report codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}